kind: Deployment
apiVersion: apps/v1
metadata:
  name: imgproxy
  labels:
    app: imgproxy
spec:
  selector:
    matchLabels:
      app: imgproxy
  template:
    metadata:
      labels:
        app: imgproxy
    spec:
      containers:
        - image: darthsim/imgproxy:latest
          imagePullPolicy: Always
          name: imgproxy
          env:
            - name: IMGPROXY_SO_REUSEPORT
              value: "true"
            - name: IMGPROXY_ENABLE_WEBP_DETECTION
              value: "true"
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: imgcache
  name: imgcache
spec:
  selector:
    matchLabels:
      app: imgcache
  template:
    metadata:
      labels:
        app: imgcache
    spec:
      volumes:
        - name: cache-volume
          emptyDir: {}
      containers:
        - image: ostermann/imgcache:latest
          imagePullPolicy: Always
          name: imgcache
          volumeMounts:
            - name: cache-volume
              mountPath: /var/cache/nginx
          env:
            - name: IMGPROXY
              value: "local-imgproxy:8080"
          ports:
            - name: http
              containerPort: 80
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate