apiVersion: v1
kind: Service
metadata:
  name: local-imgcache
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
  externalTrafficPolicy: Local
  selector:
    app: imgcache
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: local-imgproxy
spec:
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  externalTrafficPolicy: Local
  selector:
    app: imgproxy
  type: NodePort
---